software-development:
  - tl-software-development   # TODO: replace once this Technical Lead is confirmed
web3-blockchain:
  - abdul-abdi
iot-robotics:
  - khansamuel
ml-data-science:
  - wakoTheDev
cybersecurity:
  - johnie-musyoki
  - wandera-chris
